# Copyright 2013 The Flutter Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

import("//flutter/impeller/tools/impeller.gni")
import("//flutter/testing/testing.gni")


impeller_component("playground") {
  testonly = true
  include_dirs = [
    "${custom_sysroot}/usr/include/appfw",
    "${custom_sysroot}/usr/include/base",
    "${custom_sysroot}/usr/include/dali",
    "${custom_sysroot}/usr/include/dali-adaptor",
    "${custom_sysroot}/usr/include/dali-toolkit",
    "${custom_sysroot}/usr/include/dlog",
    "${custom_sysroot}/usr/include/ecore-1",
    "${custom_sysroot}/usr/include/ecore-con-1",
    "${custom_sysroot}/usr/include/ecore-evas-1",
    "${custom_sysroot}/usr/include/ecore-file-1",
    "${custom_sysroot}/usr/include/ecore-imf-1",
    "${custom_sysroot}/usr/include/ecore-imf-evas-1",
    "${custom_sysroot}/usr/include/ecore-input-1",
    "${custom_sysroot}/usr/include/ecore-input-evas-1",
    "${custom_sysroot}/usr/include/ecore-wayland-1",
    "${custom_sysroot}/usr/include/ecore-wl2-1",
    "${custom_sysroot}/usr/include/edje-1",
    "${custom_sysroot}/usr/include/eet-1",
    "${custom_sysroot}/usr/include/efl-1",
    "${custom_sysroot}/usr/include/efl-extension",
    "${custom_sysroot}/usr/include/efl-1/interfaces",
    "${custom_sysroot}/usr/include/efreet-1",
    "${custom_sysroot}/usr/include/eina-1",
    "${custom_sysroot}/usr/include/eina-1/eina",
    "${custom_sysroot}/usr/include/eldbus-1",
    "${custom_sysroot}/usr/include/elementary-1",
    "${custom_sysroot}/usr/include/emile-1",
    "${custom_sysroot}/usr/include/eo-1",
    "${custom_sysroot}/usr/include/ethumb-1",
    "${custom_sysroot}/usr/include/ethumb-client-1",
    "${custom_sysroot}/usr/include/evas-1",
    "${custom_sysroot}/usr/include/feedback",
    "${custom_sysroot}/usr/include/system",
    "${custom_sysroot}/usr/include/tzsh",
    "${custom_sysroot}/usr/include/vconf",
    "${custom_sysroot}/usr/include/wayland-extension",
  ]
  libs = [
      "base-utils-i18n",
      "capi-appfw-application",
      "capi-appfw-app-common",
      "capi-appfw-app-control",
      "capi-appfw-preference",
      "capi-base-common",
      "capi-system-info",
      "capi-system-system-settings",
      "capi-ui-efl-util",
      "dlog",
      "ecore",
      "ecore_evas",
      "ecore_imf",
      "ecore_imf_evas",
      "ecore_input",
      "ecore_wl2",
      "efl-extension",
      "eina",
      "eldbus",
      "elementary",
      "evas",
      "feedback",
      "flutter_engine",
      "tbm",
      "tdm-client",
      "tizen-extension-client",
      "vconf",
      "vulkan",
      "wayland-client",
      "EGL",
      "GLESv2",
    ]

  sources = [
    #"playground.cc",
    #"playground.h",
    "tizen_window_ecore_wl2.cc",
    "tizen_window_ecore_wl2.h",
    #"playground_impl.cc",
    #"playground_impl.h",
    "switches.cc",
    "switches.h",
    "widgets.cc",
    "widgets.h",
    "tizen_window_ecore_wl2.cc",
    "tizen_window_ecore_wl2.h",

    # Swiftshader is Vulkan backend specific but the utilities are not.
    #"backend/vulkan/swiftshader_utilities.cc",
    #"backend/vulkan/swiftshader_utilities.h",
  ]

  include_dirs = [
    "../../ci/tizen/sysroot/arm/usr/include/appfw",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-con-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-evas-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-file-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-imf-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-imf-evas-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-input-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-input-evas-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-wayland-1",
    "../../ci/tizen/sysroot/arm/usr/include/ecore-wl2-1",
    "../../ci/tizen/sysroot/arm/usr/include/eina-1",
    "../../ci/tizen/sysroot/arm/usr/include/eina-1/eina",
    "../../ci/tizen/sysroot/arm/usr/include/edje-1",
    "../../ci/tizen/sysroot/arm/usr/include/eet-1",
    "../../ci/tizen/sysroot/arm/usr/include/efl-1",
    "../../ci/tizen/sysroot/arm/usr/include/efl-extension",
    "../../ci/tizen/sysroot/arm/usr/include/efl-1/interfaces",
    "../../ci/tizen/sysroot/arm/usr/include/efreet-1",
    "../../ci/tizen/sysroot/arm/usr/include/eina-1",
    "../../ci/tizen/sysroot/arm/usr/include/eina-1/eina",
    "../../ci/tizen/sysroot/arm/usr/include/eldbus-1",
    "../../ci/tizen/sysroot/arm/usr/include/elementary-1",
    "../../ci/tizen/sysroot/arm/usr/include/emile-1",
    "../../ci/tizen/sysroot/arm/usr/include/eo-1",
    "../../ci/tizen/sysroot/arm/usr/include/ethumb-1",
    "../../ci/tizen/sysroot/arm/usr/include/ethumb-client-1",
    "../../ci/tizen/sysroot/arm/usr/include/evas-1",
    "../../ci/tizen/sysroot/arm/usr/include/feedback",
    "../../ci/tizen/sysroot/arm/usr/include/system",
    "../../ci/tizen/sysroot/arm/usr/include/tzsh",
    "../../ci/tizen/sysroot/arm/usr/include/vconf",
    "../../ci/tizen/sysroot/arm/usr/include/wayland-extension",
    "../../ci/tizen/sysroot/arm/usr/include/EGL",
    "../../ci/tizen/sysroot/arm/usr/include/GLES",
    "../../ci/tizen/sysroot/arm/usr/include/GLES2",
    "../../ci/tizen/sysroot/arm/usr/include/GLES3",
  ]

  deps = [ "../renderer/backend" ]
  

  if (impeller_enable_opengles) {
    sources += [
      "backend/gles/playground_impl_gles.cc",
      "backend/gles/playground_impl_gles.h",
    ]
  }

  if (impeller_enable_vulkan) {
    sources += [
      "backend/vulkan/playground_impl_vk.cc",
      "backend/vulkan/playground_impl_vk.h",
    ]
  }

  public_deps = [
    "../fixtures:modern_shader_fixtures",
    "../fixtures:shader_fixtures",
    "../renderer",
    "image:image_skia_backend",
    "imgui:imgui_impeller_backend",
    "//flutter/fml",
    "//flutter/testing:testing_lib",
    #"//flutter/third_party/glfw",
    #"//flutter/third_party/imgui:imgui_glfw",
  ]

  if (impeller_supports_rendering) {
    public_deps += [
      "../entity:entity_shaders",
      "../entity:framebuffer_blend_entity_shaders",
      "../entity:modern_entity_shaders",
    ]
  }

  if (is_mac) {
    frameworks = [
      "AppKit.framework",
      "QuartzCore.framework",
    ]
  }
}

impeller_component("playground_test") {
  testonly = true

  sources = [
    #"compute_playground_test.cc",
    #"compute_playground_test.h",
    "playground_test.cc",
    "playground_test.h",
  ]

  public_deps = [
    ":playground",
    "//flutter/testing:testing_lib",
  ]
}
